# Generated by Django 5.2.4 on 2025-07-10 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnic', models.CharField(max_length=20)),
                ('education', models.CharField(max_length=100)),
                ('degree', models.FileField(blank=True, null=True, upload_to='kyc/degree/')),
                ('aadhar', models.FileField(blank=True, null=True, upload_to='kyc/aadhar/')),
                ('pan', models.FileField(blank=True, null=True, upload_to='kyc/pan/')),
                ('bar', models.FileField(blank=True, null=True, upload_to='kyc/bar/')),
                ('location', models.CharField(max_length=100)),
                ('court_level', models.CharField(max_length=50)),
                ('case_types', models.CharField(max_length=200)),
                ('experience', models.CharField(max_length=50)),
                ('availability', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('profile_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('available_slots', models.JSONField(blank=True, default=dict)),
                ('languages', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
