# Generated by Django 5.2.4 on 2025-09-06 11:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapi', '0001_initial'),
        ('videosession', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_id', models.CharField(max_length=100)),
                ('sender_name', models.CharField(default='User', max_length=100)),
                ('text', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='bookingapi.booking')),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['booking', 'timestamp'], name='videosessio_booking_7fa9f3_idx')],
            },
        ),
    ]
