# Generated by Django 5.2.4 on 2025-07-13 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_feedback', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteFeedbackReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_text', models.TextField(help_text='Reply from admin/support.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feedback', models.OneToOneField(help_text='The feedback being replied to.', on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='website_feedback.websitefeedback')),
                ('responder', models.ForeignKey(help_text='The admin or support person replying to the feedback.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Website Feedback Reply',
                'verbose_name_plural': 'Website Feedback Replies',
            },
        ),
    ]
